# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main", "dev", "actions_test" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
      with:
        arguments: build
        
  test_one:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          java-package: jdk
          cache: 'gradle'
          
      - name: Compile Gradle tests
        # before running tests, try to compile the solution
        run: ./gradlew compileTestJava --continue --info

      - name: Run Gradle tests
        # we want gradle to do as much as possible, and show info about failing tests
        run: ./gradlew check --continue --info
        # we want to publish report even if tests are failing
        continue-on-error: true
