name: Simple CI

on:
  push:
    branches: [ "main", "dev", "actions_test" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  tests_with_report:
  
    runs-on: ubuntu-20.04 # to lock kernel version somehow
    timeout-minutes: 20
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11 # for back comparability with initial task
        distribution: 'adopt'

    - name: Run all tests
      run: ./gradlew check
      continue-on-error: true
      
    - name: Archieve test report
      uses: actions/upload-artifact@v2
      with:
        name: Test report
        path: build/reports/tests/test
